# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

project_dir = "CriteoPublisherSdk"

platform :ios do
  desc %(Run tests:
    - format_check: check code formatting
    - multi_scan: run Unit & Functional tests
  )
  lane :test do
    format_check
    multi_scan(
      scheme: "CriteoPublisherSdk",
      try_count: 3, parallel_testrun_count: 2
    )
  end

  desc %(Check code format)
  lane :format_check do
    run_clang_format(
      script_path: "tools/clang-format/run-clang-format.py",
      extensions: "h,m",
      paths: ["#{project_dir}"],
      executable: "tools/clang-format/clang-format",
    )
  end

  desc %(Format code)
  lane :format do
    files = []
    Dir.chdir("..") do
      files = Dir.glob("#{project_dir}/**/*.{h,m}")
    end

    clang_format(
      clang_format_path: "tools/clang-format/clang-format",
      inplace: true,
      style: "file",
      verbose: true,
      files: files,
    )
  end

  desc %(Extract last version changelog)
  lane :last_changelog do
    changelog = File.open("../CHANGELOG.md").read
    last_changelog = changelog
        .split(/----*\n/)[1] # Get last version section
        .lines[2..-1].join   # Remove first line that contains version
        .strip!
    File.write('../last-changelog.md', last_changelog)
  end
end
