# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Run Fuji Tests"
  lane :fuji_tests do |options|
    multi_scan(
      scheme: options[:scheme],
      try_count: 3,
      output_directory: "build/reports",
      output_files: "tests.html,junit.xml"
    )
  end

  desc "Run Pre Submit Tests"
  lane :presubmit_tests do
    fuji_tests(scheme: "PresubmitTests")
  end
  desc "Run Post Submit Tests"
  lane :postsubmit_tests do
    fuji_tests(scheme: "PostsubmitTests")
  end
end
