platform :ios, '13.0'

workspace 'CriteoAdViewer'

target 'CriteoAdViewer' do
  project 'CriteoAdViewer'

  pod 'CriteoPublisherSdk', '~> 6.1.2'
  # pod 'CriteoPublisherSdk', :git => 'https://github.com/criteo/ios-publisher-sdk.git' #, :branch => ''
  pod 'Google-Mobile-Ads-SDK'
  pod 'Eureka'
end

