name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Ruby setup
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Bundle cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Cocoapods cache
      uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Cocoapods install
      run: |
        bundle exec fastlane run cocoapods

     # Testing...
    - name: Archive
      run: |
        ./scripts/archive.sh

    - name: Release
      run: |
        bundle exec fastlane release ref:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
