name: Release on CocoaPods

on:
  release:
    types: [published]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer

jobs:
  release-cocoapods:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Bundle setup
      uses: ./.github/actions/setup-bundle

    - name: CocoaPods Release
      run: |
        bundle exec fastlane release_cocoapods
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
